name: Build .NET

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: 构建镜像
      run: docker build -t cuqan6615/cicd:latest .

    - name: Push Docker image
      run: docker push cquan6615/cicd:latest

